[package]
name = "bls_signatures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blst = "0.3.11"
hex = "0.4.3"
rand = "0.8.5"
